src-git luci https://github.com/immortalwrt/luci.git
src-git packages https://github.com/immortalwrt/packages.git
src-git routing https://github.com/immortalwrt/routing.git
# src-git nss_packages https://github.com/bitthief/nss-packages.git
src-git nss_packages https://github.com/AgustinLorenzo/nss-packages.git

# src-git-full packages https://git.openwrt.org/feed/packages.git
# src-git-full luci https://git.openwrt.org/project/luci.git
# src-git-full routing https://git.openwrt.org/feed/routing.git
# src-git-full telephony https://git.openwrt.org/feed/telephony.git
# src-git-full nss_packages https://github.com/bitthief/nss-packages.git
